FROM python:3.10-slim
WORKDIR /app

COPY family-service/requirements.txt .
COPY family-service/app_mom.py .
COPY family-service/app_dad.py .
COPY family-service/app_bro.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app_mom.py"]